export enum ActionType {
  CARD_DRAWN = 'CARD_DRAWN',
  CONNECTED = 'CONNECTED',
  CONNECTION_FAILED = 'CONNECTION_FAILED',
  DRAWING_CARD = 'DRAWING_CARD',
  END_TURN = 'END_TURN',
  EVENT = 'EVENT',
  GAME_STARTED = 'GAME_STARTED',
  JOIN_ROOM = 'JOIN_ROOM',
  JOINED_ROOM = 'JOINED_ROOM',
  JOINING = 'JOINING',
  LOADING = 'LOADING',
  ROOM_UPDATED = 'ROOM_UPDATED',
  SET_CARD_IMAGES = 'SET_CARD_IMAGES',
  TURN_ENDED = 'TURN_ENDED'
}
