export enum ActionType {
  CARD_DRAWN = 'CARD_DRAWN',
  CONNECTED = 'CONNECTED',
  DRAWING_CARD = 'DRAWING_CARD',
  GAME_STARTED = 'GAME_STARTED',
  JOIN_ROOM = 'JOIN_ROOM',
  JOINED_ROOM = 'JOINED_ROOM',
  JOINING = 'JOINING',
  LOADING = 'LOADING',
  ROOM_UPDATED = 'ROOM_UPDATED'
}
