export enum ActionType {
  CONNECTED = 'CONNECTED',
  GAME_STARTED = 'GAME_STARTED',
  JOIN_ROOM = 'JOIN_ROOM',
  JOINED_ROOM = 'JOINED_ROOM',
  JOINING = 'JOINING',
  LOADING = 'LOADING',
  ROOM_UPDATED = 'ROOM_UPDATED'
}
